[package]
name = "sha-on-cq"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/bin/render_table.rs"
name = "render_table"

[dependencies]
sha2 = { version = "0.10.8" }
tabled = { version = "0.15.0", features = ["ansi"] }
